name: ClashForge

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    paths:
      - '.github/workflows/ClashForge.yml'
      - 'ClashForge.py'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  INPUT: ${{ vars.INPUT }}

jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.10'

      - name: Install requirements.txt
        run: |
          pip install -r ./requirements2.txt
        continue-on-error: false

      - name: Setup mihomo
        run: |
          ls -l ./mihomo
          gunzip -f ./mihomo/mihomo-linux-amd64-compatible-v1.19.13.gz
          chmod +x ./mihomo/mihomo-linux-amd64-compatible-v1.19.13
          ls -l ./mihomo
        continue-on-error: false

      - name: Run ClashForge.py
        run: |
          python ClashForge.py
        continue-on-error: false

      - name: Commit and push file
        run: |
          git config user.name "github-actions[bot]"
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # ⚠️ 修复：删除了 git reset --hard 和 git clean -fd
          
          git add clash_config.yaml
          git add clash_config.yaml.json
          
          if ! git diff --staged --quiet; then
            echo "No changes detected, creating an empty commit to force update."
            git commit --allow-empty -m "update: No changes detected"
          else
            git commit -m "update"
          fi
          
          for i in {1..3}; do
            echo "Attempt $i to pull, rebase, and push..."
            git pull --rebase origin main
            
            if [ $? -eq 0 ]; then
              git push origin main
              if [ $? -eq 0 ]; then
                echo "Push successful on attempt $i."
                exit 0
              fi
            fi
            
            sleep 5
          done
          
          echo "Failed to push after multiple attempts. Manual intervention may be required."
          exit 1
